name: lint, test, build

on:
  push:
  pull_request:

jobs:
  homeworks:
    name: Rust project lint, test and build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        toolchain:
          - stable

    steps:
      - uses: actions/checkout@v3
      - name: "Rustup update"
        run: rustup update ${{ matrix.toolchain }} && rustup default ${{ matrix.toolchain }}
        if: always()
      - name: "Start clippy and format check"
        run: "cargo clippy && cargo fmt --check --verbose"
        if: always()
      - name: "Run integration test"
        run: cargo test --test integration
        if: always()
      - name: "Start build in release mode"
        run: cargo build --verbose --release
